/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./../components/Auth/index.vue')['default']
    AuthAll: typeof import('./../components/AuthAll/index.vue')['default']
    ControlBar: typeof import('./../components/Vue3Amap/components/ControlBar/index.vue')['default']
    FenceMap: typeof import('./../components/FenceMap/index.vue')['default']
    FileUpload: typeof import('./../components/FileUpload/index.vue')['default']
    FitView: typeof import('./../components/Vue3Amap/components/FitView/index.vue')['default']
    FixedActionBar: typeof import('./../components/FixedActionBar/index.vue')['default']
    FormModal: typeof import('./../components/FormModal/index.vue')['default']
    Geolocation: typeof import('./../components/Vue3Amap/components/Geolocation/index.vue')['default']
    HButton: typeof import('./../layouts/ui-kit/HButton.vue')['default']
    HCheckList: typeof import('./../layouts/ui-kit/HCheckList.vue')['default']
    HDialog: typeof import('./../layouts/ui-kit/HDialog.vue')['default']
    HDropdown: typeof import('./../layouts/ui-kit/HDropdown.vue')['default']
    HDropdownMenu: typeof import('./../layouts/ui-kit/HDropdownMenu.vue')['default']
    HInput: typeof import('./../layouts/ui-kit/HInput.vue')['default']
    HKbd: typeof import('./../layouts/ui-kit/HKbd.vue')['default']
    HSelect: typeof import('./../layouts/ui-kit/HSelect.vue')['default']
    HSlideover: typeof import('./../layouts/ui-kit/HSlideover.vue')['default']
    HTabList: typeof import('./../layouts/ui-kit/HTabList.vue')['default']
    HToggle: typeof import('./../layouts/ui-kit/HToggle.vue')['default']
    HTooltip: typeof import('./../layouts/ui-kit/HTooltip.vue')['default']
    ImagePreview: typeof import('./../components/ImagePreview/index.vue')['default']
    ImagesUpload: typeof import('./../components/ImagesUpload/index.vue')['default']
    ImageUpload: typeof import('./../components/ImageUpload/index.vue')['default']
    Map: typeof import('./../components/Vue3Amap/components/Map/index.vue')['default']
    MapType: typeof import('./../components/Vue3Amap/components/MapType/index.vue')['default']
    Marker: typeof import('./../components/Vue3Amap/components/Marker/index.vue')['default']
    NotAllowed: typeof import('./../components/NotAllowed/index.vue')['default']
    PageHeader: typeof import('./../components/PageHeader/index.vue')['default']
    PageMain: typeof import('./../components/PageMain/index.vue')['default']
    PageMainFull: typeof import('./../components/PageMainFull/index.vue')['default']
    PcasCascader: typeof import('./../components/PcasCascader/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scale: typeof import('./../components/Vue3Amap/components/Scale/index.vue')['default']
    Search: typeof import('./../components/Vue3Amap/components/Search/index.vue')['default']
    SearchBar: typeof import('./../components/SearchBar/index.vue')['default']
    ServerImg: typeof import('./../components/ServerImg/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    SystemInfo: typeof import('./../components/SystemInfo/index.vue')['default']
    Toolbar: typeof import('./../components/Vue3Amap/components/Toolbar/index.vue')['default']
    Trend: typeof import('./../components/Trend/index.vue')['default']
    Vector: typeof import('./../components/Vue3Amap/components/Vector/index.vue')['default']
  }
}
